# Generated by Django 3.1.7 on 2021-03-25 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locationsadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facilities',
            name='CreatedBy',
        ),
        migrations.RemoveField(
            model_name='facilities',
            name='FacilitiesPropertyID',
        ),
        migrations.RemoveField(
            model_name='facilities',
            name='UpdatedAt',
        ),
        migrations.AddField(
            model_name='property',
            name='AgeOfProperty',
            field=models.FloatField(default=0.0, verbose_name='Age of the Property'),
        ),
        migrations.AddField(
            model_name='property',
            name='DateOfPossesion',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Possession'),
        ),
        migrations.AddField(
            model_name='property',
            name='Parking',
            field=models.IntegerField(default=0, verbose_name='Parking'),
        ),
        migrations.AddField(
            model_name='property',
            name='PriceUnit',
            field=models.CharField(choices=[('Cr', 'Cr'), ('L', 'L'), ('K', 'K')], default='', max_length=250, verbose_name='Price Unit'),
        ),
        migrations.AddField(
            model_name='property',
            name='PropertyAddress1',
            field=models.CharField(default='', max_length=250, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='property',
            name='Furnished',
            field=models.CharField(choices=[('Furnished', 'Furnished'), ('Unfurnished', 'Unfurnished'), ('Semi-Furnished', 'Semi-Furnished')], default='', max_length=250, verbose_name='Furnished'),
        ),
        migrations.AlterField(
            model_name='property',
            name='PossessionStatus',
            field=models.CharField(choices=[('Ready To Move', 'Ready to move'), ('Under Construction', 'Under Construction')], default='', max_length=250, verbose_name='Possession Status'),
        ),
        migrations.AlterField(
            model_name='property',
            name='Price',
            field=models.FloatField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='property',
            name='PropertyAddress',
            field=models.CharField(default='', max_length=250, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='property',
            name='TransactionType',
            field=models.CharField(choices=[('BUY', 'BUY'), ('RENT', 'RENT')], default='', max_length=250, verbose_name='Transaction Type'),
        ),
        migrations.CreateModel(
            name='PropFacilities',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('FacilityID', models.ManyToManyField(to='locationsadmin.Facilities')),
                ('PropertyID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locationsadmin.property', verbose_name='Select Property')),
            ],
            options={
                'verbose_name': 'PROPERTY FACILITY',
                'verbose_name_plural': 'PROPERTY FACILITY',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PropertyImags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Images', models.ImageField(default='', upload_to='', verbose_name='propertyIndividualImages')),
                ('TheProperty', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='locationsadmin.property')),
            ],
        ),
    ]
