# Generated by Django 3.1.7 on 2021-03-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationsadmin', '0002_auto_20210325_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='AgeOfProperty',
        ),
        migrations.RemoveField(
            model_name='property',
            name='DateOfPossesion',
        ),
        migrations.AddField(
            model_name='property',
            name='FacilityID',
            field=models.ManyToManyField(to='locationsadmin.Facilities'),
        ),
        migrations.AddField(
            model_name='property',
            name='FurnishedDesc',
            field=models.TextField(blank=True, default='', verbose_name='Furnished Description'),
        ),
        migrations.AddField(
            model_name='property',
            name='IsVisible',
            field=models.BooleanField(default=True, verbose_name='Is Visible?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='Availability',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='property',
            name='Balcony',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='Bathroom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='Bedroom',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='Furnished',
            field=models.CharField(choices=[('Furnished', 'Furnished'), ('Semi Furnished', 'Semi Furnished'), ('Unfurnished', 'Unfurnished')], default='', max_length=250, verbose_name='Furnished'),
        ),
        migrations.AlterField(
            model_name='property',
            name='PossessionStatus',
            field=models.CharField(choices=[('Ready to Move', 'Ready to Move'), ('Under Construction', 'Under Construction')], default='', max_length=250, verbose_name='Posession Status'),
        ),
        migrations.AlterField(
            model_name='property',
            name='PropertyAddress',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='property',
            name='PropertyAddress1',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='property',
            name='PropertyImage',
            field=models.ImageField(default='building.png', upload_to='propertybanner'),
        ),
        migrations.AlterField(
            model_name='property',
            name='PropertySize',
            field=models.FloatField(blank=True, verbose_name='Super Builtup'),
        ),
        migrations.AlterField(
            model_name='property',
            name='ShortDescription',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Short Description'),
        ),
    ]
