# Generated by Django 3.1.7 on 2021-03-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationsadmin', '0003_auto_20210327_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='FacilityEight',
            field=models.BooleanField(default=True, verbose_name='Swimming Pool'),
        ),
        migrations.AddField(
            model_name='property',
            name='FacilityFive',
            field=models.BooleanField(default=True, verbose_name='Spa treatment room'),
        ),
        migrations.AddField(
            model_name='property',
            name='FacilityFour',
            field=models.BooleanField(default=True, verbose_name='Indoor games area'),
        ),
        migrations.AddField(
            model_name='property',
            name='FacilityNine',
            field=models.BooleanField(default=True, verbose_name='Terrace Garden'),
        ),
        migrations.AddField(
            model_name='property',
            name='FacilityOne',
            field=models.BooleanField(default=True, verbose_name='Party hall'),
        ),
        migrations.AddField(
            model_name='property',
            name='FacilitySeven',
            field=models.BooleanField(default=True, verbose_name='Children’s play area'),
        ),
        migrations.AddField(
            model_name='property',
            name='FacilitySix',
            field=models.BooleanField(default=True, verbose_name='Swimming pool and kids pool'),
        ),
        migrations.AddField(
            model_name='property',
            name='FacilityTen',
            field=models.BooleanField(default=True, verbose_name='Shopping Centre'),
        ),
        migrations.AddField(
            model_name='property',
            name='FacilityThree',
            field=models.BooleanField(default=True, verbose_name='Business Centre/ Library'),
        ),
        migrations.AddField(
            model_name='property',
            name='FacilityTwo',
            field=models.BooleanField(default=True, verbose_name='Fully equipped gymnasium'),
        ),
        migrations.AlterField(
            model_name='property',
            name='FacilityID',
            field=models.ManyToManyField(blank=True, to='locationsadmin.Facilities'),
        ),
        migrations.AlterField(
            model_name='property',
            name='PropertySize',
            field=models.FloatField(blank=True, null=True, verbose_name='Super Builtup'),
        ),
    ]
