# Generated by Django 3.1.7 on 2021-04-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationsadmin', '0004_auto_20210331_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='FurnishEight',
            field=models.BooleanField(blank=True, default=True, verbose_name='Dining Table'),
        ),
        migrations.AddField(
            model_name='property',
            name='FurnishEleven',
            field=models.BooleanField(blank=True, default=True, verbose_name='Fridge'),
        ),
        migrations.AddField(
            model_name='property',
            name='FurnishFive',
            field=models.BooleanField(blank=True, default=True, verbose_name='Chimney'),
        ),
        migrations.AddField(
            model_name='property',
            name='FurnishFour',
            field=models.BooleanField(blank=True, default=True, verbose_name='Curtains'),
        ),
        migrations.AddField(
            model_name='property',
            name='FurnishNine',
            field=models.BooleanField(blank=True, default=True, verbose_name='Stove'),
        ),
        migrations.AddField(
            model_name='property',
            name='FurnishOne',
            field=models.BooleanField(blank=True, default=True, verbose_name='Washing Machine'),
        ),
        migrations.AddField(
            model_name='property',
            name='FurnishSeven',
            field=models.BooleanField(blank=True, default=True, verbose_name='Sofa'),
        ),
        migrations.AddField(
            model_name='property',
            name='FurnishSix',
            field=models.BooleanField(blank=True, default=True, verbose_name='Exhaust Fan'),
        ),
        migrations.AddField(
            model_name='property',
            name='FurnishTen',
            field=models.BooleanField(blank=True, default=True, verbose_name='Modular Kitchen'),
        ),
        migrations.AddField(
            model_name='property',
            name='FurnishThingFive',
            field=models.IntegerField(default=0, verbose_name='AC'),
        ),
        migrations.AddField(
            model_name='property',
            name='FurnishThingFour',
            field=models.IntegerField(default=0, verbose_name='Light'),
        ),
        migrations.AddField(
            model_name='property',
            name='FurnishThingOne',
            field=models.IntegerField(default=0, verbose_name='Wardrobe'),
        ),
        migrations.AddField(
            model_name='property',
            name='FurnishThingSeven',
            field=models.IntegerField(default=0, verbose_name='TV'),
        ),
        migrations.AddField(
            model_name='property',
            name='FurnishThingSix',
            field=models.IntegerField(default=0, verbose_name='Geyser'),
        ),
        migrations.AddField(
            model_name='property',
            name='FurnishThingThree',
            field=models.IntegerField(default=0, verbose_name='Fans'),
        ),
        migrations.AddField(
            model_name='property',
            name='FurnishThingTwo',
            field=models.IntegerField(default=0, verbose_name='Beds'),
        ),
        migrations.AddField(
            model_name='property',
            name='FurnishThree',
            field=models.BooleanField(blank=True, default=True, verbose_name='Microwave'),
        ),
        migrations.AddField(
            model_name='property',
            name='FurnishTwo',
            field=models.BooleanField(blank=True, default=True, verbose_name='Water Purifier'),
        ),
        migrations.AlterField(
            model_name='property',
            name='FacilityID',
            field=models.ManyToManyField(blank=True, to='locationsadmin.Facilities', verbose_name='Facility Name'),
        ),
        migrations.AlterField(
            model_name='property',
            name='TxnType',
            field=models.CharField(choices=[('BUY', 'BUY'), ('RENT', 'RENT')], max_length=200, verbose_name='Buy / Rent'),
        ),
    ]
