# Generated by Django 3.1.7 on 2021-04-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationsadmin', '0005_auto_20210403_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='PossessionDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='TxnType',
            field=models.CharField(choices=[('BUY', 'BUY'), ('RENT', 'RENT')], default='', max_length=200, verbose_name='Buy / Rent (What your users see)'),
        ),
    ]
