# Generated by Django 3.1.7 on 2021-04-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationsadmin', '0006_auto_20210405_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='Deposit',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Deposit (Applicable on RENT Properties only)'),
        ),
    ]
