# Generated by Django 3.1.7 on 2021-04-27 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locationsadmin', '0008_auto_20210408_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='AgentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locationsadmin.agentref', verbose_name='AGENT'),
        ),
        migrations.AlterField(
            model_name='property',
            name='Area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locationsadmin.area', verbose_name='AREA LOCATION'),
        ),
        migrations.AlterField(
            model_name='property',
            name='Availability',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='AVAILABILITY'),
        ),
        migrations.AlterField(
            model_name='property',
            name='Balcony',
            field=models.IntegerField(default=0, verbose_name='BALCONY'),
        ),
        migrations.AlterField(
            model_name='property',
            name='Bathroom',
            field=models.IntegerField(default=0, verbose_name='BATHROOM'),
        ),
        migrations.AlterField(
            model_name='property',
            name='Bedroom',
            field=models.IntegerField(default=0, verbose_name='BEDROOM'),
        ),
        migrations.AlterField(
            model_name='property',
            name='BuiltUpArea',
            field=models.FloatField(verbose_name='BUILTUP AREA'),
        ),
        migrations.AlterField(
            model_name='property',
            name='CarpetArea',
            field=models.FloatField(verbose_name='CARPET AREA'),
        ),
        migrations.AlterField(
            model_name='property',
            name='CustomerFeast',
            field=models.CharField(choices=[('Any', 'Any'), ('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], default='', max_length=250, verbose_name='CUSTOMER FEAST'),
        ),
        migrations.AlterField(
            model_name='property',
            name='CustomerStatus',
            field=models.CharField(choices=[('Any', 'Any'), ('Family', 'Family'), ('Bachelor', 'Bachelor')], default='', max_length=250, verbose_name='CUSTOMER STATUS'),
        ),
        migrations.AlterField(
            model_name='property',
            name='Deposit',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='DEPOSIT AMOUNT'),
        ),
        migrations.AlterField(
            model_name='property',
            name='FacilityFive',
            field=models.BooleanField(default=True, verbose_name='Spa Treatment Room'),
        ),
        migrations.AlterField(
            model_name='property',
            name='FacilityFour',
            field=models.BooleanField(default=True, verbose_name='Indoor Games Grea'),
        ),
        migrations.AlterField(
            model_name='property',
            name='FacilityID',
            field=models.ManyToManyField(blank=True, to='locationsadmin.Facilities', verbose_name='FACILITY NAME'),
        ),
        migrations.AlterField(
            model_name='property',
            name='FacilityOne',
            field=models.BooleanField(default=True, verbose_name='Party Hall'),
        ),
        migrations.AlterField(
            model_name='property',
            name='FacilitySeven',
            field=models.BooleanField(default=True, verbose_name='Children’s Play Area'),
        ),
        migrations.AlterField(
            model_name='property',
            name='FacilitySix',
            field=models.BooleanField(default=True, verbose_name='Swimming Pool and Kids Pool'),
        ),
        migrations.AlterField(
            model_name='property',
            name='FacilityThree',
            field=models.BooleanField(default=True, verbose_name='Business Centre/Library'),
        ),
        migrations.AlterField(
            model_name='property',
            name='FacilityTwo',
            field=models.BooleanField(default=True, verbose_name='Fully Equipped Gymnasium'),
        ),
        migrations.AlterField(
            model_name='property',
            name='FloorNumber',
            field=models.CharField(default='', max_length=250, verbose_name='FLOOR NUMBER'),
        ),
        migrations.AlterField(
            model_name='property',
            name='FurnishThingFour',
            field=models.IntegerField(default=0, verbose_name='LIGHT'),
        ),
        migrations.AlterField(
            model_name='property',
            name='FurnishThingOne',
            field=models.IntegerField(default=0, verbose_name='WARDROBE'),
        ),
        migrations.AlterField(
            model_name='property',
            name='FurnishThingSix',
            field=models.IntegerField(default=0, verbose_name='GEYSER'),
        ),
        migrations.AlterField(
            model_name='property',
            name='FurnishThingThree',
            field=models.IntegerField(default=0, verbose_name='FANS'),
        ),
        migrations.AlterField(
            model_name='property',
            name='FurnishThingTwo',
            field=models.IntegerField(default=0, verbose_name='BEDS'),
        ),
        migrations.AlterField(
            model_name='property',
            name='Furnished',
            field=models.CharField(choices=[('Furnished', 'Furnished'), ('Semi Furnished', 'Semi Furnished'), ('Unfurnished', 'Unfurnished')], default='', max_length=250, verbose_name='FURNISHED'),
        ),
        migrations.AlterField(
            model_name='property',
            name='FurnishedDesc',
            field=models.TextField(blank=True, default='', verbose_name='FURNISHED DESCRIPTION'),
        ),
        migrations.AlterField(
            model_name='property',
            name='InGallery',
            field=models.BooleanField(default=False, verbose_name='IN GALLERY?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='IsVisible',
            field=models.BooleanField(default=True, verbose_name='IS VISIBLE?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='OurProperty',
            field=models.BooleanField(default=False, verbose_name='OUR PROPERTY?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='Parking',
            field=models.IntegerField(default=0, verbose_name='PARKING'),
        ),
        migrations.AlterField(
            model_name='property',
            name='PetsAllowed',
            field=models.CharField(choices=[('Allowed', 'Allowed'), ('Not Allowed', 'Not Allowed')], default='', max_length=250, verbose_name='PET ALLOWED?'),
        ),
        migrations.AlterField(
            model_name='property',
            name='PossessionDate',
            field=models.DateField(blank=True, null=True, verbose_name='POSSESSION DATE'),
        ),
        migrations.AlterField(
            model_name='property',
            name='PossessionStatus',
            field=models.CharField(choices=[('Ready to Move', 'Ready to Move'), ('Under Construction', 'Under Construction')], default='', max_length=250, verbose_name='POSSESSION STATUS'),
        ),
        migrations.AlterField(
            model_name='property',
            name='Price',
            field=models.FloatField(blank=True, default='', null=True, verbose_name='PRICE'),
        ),
        migrations.AlterField(
            model_name='property',
            name='PriceUnit',
            field=models.CharField(choices=[('Cr', 'Cr'), ('L', 'L'), ('K', 'K')], default='', max_length=250, verbose_name='PRICE UNIT'),
        ),
        migrations.AlterField(
            model_name='property',
            name='PropertyAddress',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='ADDRESS LINE 1'),
        ),
        migrations.AlterField(
            model_name='property',
            name='PropertyAddress1',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='ADDRESS LINE 2'),
        ),
        migrations.AlterField(
            model_name='property',
            name='PropertyImage',
            field=models.ImageField(default='building.png', upload_to='propertybanner', verbose_name='PROPERTY IMAGE'),
        ),
        migrations.AlterField(
            model_name='property',
            name='PropertyLocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locationsadmin.locationsref', verbose_name='PROPERTY LOCATION'),
        ),
        migrations.AlterField(
            model_name='property',
            name='PropertySize',
            field=models.FloatField(blank=True, null=True, verbose_name='SUPER BUILT UP'),
        ),
        migrations.AlterField(
            model_name='property',
            name='PropertyType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locationsadmin.propertytyperef', verbose_name='PROPERTY TYPE'),
        ),
        migrations.AlterField(
            model_name='property',
            name='RateSQFT',
            field=models.FloatField(verbose_name='RATE PER SQRFT'),
        ),
        migrations.AlterField(
            model_name='property',
            name='RentAmount',
            field=models.FloatField(blank=True, null=True, verbose_name='RENT AMOUNT'),
        ),
        migrations.AlterField(
            model_name='property',
            name='RentPossessionDate',
            field=models.DateField(blank=True, null=True, verbose_name='RENT POSSESSION DATE'),
        ),
        migrations.AlterField(
            model_name='property',
            name='ShortDescription',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='SHORT DESCRIPTION'),
        ),
        migrations.AlterField(
            model_name='property',
            name='Title',
            field=models.CharField(max_length=5000, verbose_name='PROPERTY TITLE'),
        ),
        migrations.AlterField(
            model_name='property',
            name='TotalFloor',
            field=models.CharField(default='', max_length=250, verbose_name='TOTAL FLOORS'),
        ),
        migrations.AlterField(
            model_name='property',
            name='TransactionType',
            field=models.CharField(choices=[('BUY', 'BUY'), ('RENT', 'RENT')], default='', max_length=250, verbose_name='TRANSACTION TYPE'),
        ),
        migrations.AlterField(
            model_name='property',
            name='TxnType',
            field=models.CharField(choices=[('BUY', 'BUY'), ('RENT', 'RENT')], default='', max_length=200, verbose_name='TRANSACTION STATUS'),
        ),
    ]
