# Generated by Django 3.1.7 on 2021-04-28 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locationsadmin', '0010_property_rentamountunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='STID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locationsadmin.states', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='property',
            name='Area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='locationsadmin.area', verbose_name='AREA'),
        ),
    ]
