# Generated by Django 3.1.7 on 2021-04-28 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locationsadmin', '0011_auto_20210428_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='BitStatus',
        ),
    ]
