# Generated by Django 3.1.7 on 2021-05-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationsadmin', '0012_remove_cities_bitstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='ShortDescription',
            field=models.TextField(blank=True, default='', max_length=5000, verbose_name='SHORT DESCRIPTION'),
        ),
    ]
