# Generated by Django 3.1.7 on 2021-06-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationsadmin', '0014_auto_20210604_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='PriceCalculatedAmount',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='PRICE AMOUNT CALCULATED'),
        ),
        migrations.AddField(
            model_name='property',
            name='RentCalculatedAmount',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='RENT AMOUNT CALCULATED'),
        ),
        migrations.AlterField(
            model_name='property',
            name='PriceUnit',
            field=models.CharField(choices=[('Cr', 'Cr'), ('Lakhs', 'Lakhs'), ('K', 'K')], default='', max_length=250, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='property',
            name='RentAmountUnit',
            field=models.CharField(choices=[('Cr', 'Cr'), ('Lakhs', 'Lakhs'), ('K', 'K')], default='', max_length=250, verbose_name=''),
        ),
    ]
