# Generated by Django 3.1.7 on 2021-07-31 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationsadmin', '0015_auto_20210626_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPhotos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhotoTitle', models.CharField(max_length=255)),
                ('Photo', models.ImageField(upload_to='eventphotos')),
            ],
        ),
    ]
