# Generated by Django 3.1.7 on 2021-08-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationsadmin', '0017_auto_20210731_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventYoutubeVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('YoutubeTitle', models.CharField(max_length=255)),
                ('YoutubeUrl', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'EVENT YOUTUBE VIDEOS',
                'verbose_name_plural': 'EVENT YOUTUBE VIDEO',
            },
        ),
        migrations.AlterField(
            model_name='property',
            name='FacilityFour',
            field=models.BooleanField(default=True, verbose_name='Indoor Games Area'),
        ),
    ]
